module Main exposing (..)

-- Press buttons to increment and decrement a counter.
--
-- Read how it works:
--   https://guide.elm-lang.org/architecture/buttons.html
--


import Browser
import Html exposing (Html, button, div, text, textarea, b, h1, h2, table, tr, th, td, br, span)
import Html.Attributes exposing (attribute, id, class)
import Html.Events exposing (onClick)



-- MAIN


main =
  Browser.sandbox { init = init, update = update, view = view }



-- MODEL


type alias Model = String


init : Model
init =
  ""  -- Start with nothing in the textbox.



-- UPDATE


type Msg
  = 
  InsertText String


update : Msg -> Model -> Model
update msg model =
  case msg of
    InsertText str -> 
      model ++ str



-- VIEW


view : Model -> Html Msg
view model =
  div []
            [ textarea [ id "screen"] 
                [text (model) ]
            , b []
                [ text "Press buttons below to write text here." ]
            , h1 []
                [ text "International Phonetic Alphabet" ]
            , h2 []
                [ text "Consonants (Pulmonic)" ]
            , table [ attribute "style" "border: 1px solid black;" ]
                [ tr []
                    [ th []
                        []
                    , th []
                        [ text "Bilabial        " ]
                    , th []
                        [ text "Labio-dental        " ]
                    , th []
                        [ text "Dental        " ]
                    , th []
                        [ text "Alveolar        " ]
                    , th []
                        [ text "Post-alveolar        " ]
                    , th []
                        [ text "Retroflex        " ]
                    , th []
                        [ text "Palatal        " ]
                    , th []
                        [ text "Velar        " ]
                    , th []
                        [ text "Uvular        " ]
                    , th []
                        [ text "Pharyngeal        " ]
                    , th []
                        [ text "Glottal        " ]
                    ]
                , tr []
                    [ th []
                        [ text "Plosive" ]
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "p") ]
                            [ text "p" ]
                        , button [ class "voiced", onClick (InsertText "b") ]
                            [ text "b" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "t") ]
                            [ text "t" ]
                        , button [ class "voiced", onClick (InsertText "d") ]
                            [ text "d" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "ʈ") ]
                            [ text "ʈ" ]
                        , button [ class "voiced", onClick (InsertText "ɖ") ]
                            [ text "ɖ" ]
                        ]
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "c") ]
                            [ text "c" ]
                        , button [ class "voiced", onClick (InsertText "ɟ") ]
                            [ text "ɟ" ]
                        ]
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "k") ]
                            [ text "k" ]
                        , button [ class "voiced", onClick (InsertText "g") ]
                            [ text "g" ]
                        ]
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "q") ]
                            [ text "q" ]
                        , button [ class "voiced", onClick (InsertText "ɢ") ]
                            [ text "ɢ" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "ʔ") ]
                            [ text "ʔ" ]
                        , button [ attribute "style" "visibility: hidden;" ]
                            []
                        ]
                    ]
                , tr []
                    [ th []
                        [ text "Nasal" ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "m") ]
                            [ text "m" ]
                        ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "ɱ") ]
                            [ text "ɱ" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "n") ]
                            [ text "n" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "ɳ") ]
                            [ text "ɳ" ]
                        ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "ɲ") ]
                            [ text "ɲ" ]
                        ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "ɴ") ]
                            [ text "ɴ" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    ]
                , tr []
                    [ th []
                        [ text "Trill" ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "ʙ") ]
                            [ text "ʙ" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "r") ]
                            [ text "r" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "ʀ") ]
                            [ text "ʀ" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    ]
                , tr []
                    [ th []
                        [ text "Tap or Flap" ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "ⱱ") ]
                            [ text "ⱱ" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "ɾ") ]
                            [ text "ɾ" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "ɽ") ]
                            [ text "ɽ" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    ]
                , tr []
                    [ th []
                        [ text "Fricative" ]
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "ɸ") ]
                            [ text "ɸ" ]
                        , button [ class "voiced", onClick (InsertText "β") ]
                            [ text "β" ]
                        ]
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "f") ]
                            [ text "f" ]
                        , button [ class "voiced", onClick (InsertText "v") ]
                            [ text "v" ]
                        ]
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "θ") ]
                            [ text "θ" ]
                        , button [ class "voiced", onClick (InsertText "ð") ]
                            [ text "ð" ]
                        ]
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "s") ]
                            [ text "s" ]
                        , button [ class "voiced", onClick (InsertText "z") ]
                            [ text "z" ]
                        ]
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "ʃ") ]
                            [ text "ʃ" ]
                        , button [ class "voiced", onClick (InsertText "ʒ") ]
                            [ text "ʒ" ]
                        ]
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "ʂ") ]
                            [ text "ʂ" ]
                        , button [ class "voiced", onClick (InsertText "ʐ") ]
                            [ text "ʐ" ]
                        ]
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "ç") ]
                            [ text "ç" ]
                        , button [ class "voiced", onClick (InsertText "ʝ") ]
                            [ text "ʝ" ]
                        ]
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "x") ]
                            [ text "x" ]
                        , button [ class "voiced", onClick (InsertText "ɣ") ]
                            [ text "ɣ" ]
                        ]
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "χ") ]
                            [ text "χ" ]
                        , button [ class "voiced", onClick (InsertText "ʁ") ]
                            [ text "ʁ" ]
                        ]
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "ħ") ]
                            [ text "ħ" ]
                        , button [ class "voiced", onClick (InsertText "ʕ") ]
                            [ text "ʕ" ]
                        ]
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "h") ]
                            [ text "h" ]
                        , button [ class "voiced", onClick (InsertText "ɦ") ]
                            [ text "ɦ" ]
                        ]
                    ]
                , tr []
                    [ th []
                        [ text "Lateral Fricative" ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        [ button [ class "voiceless", onClick (InsertText "ɬ") ]
                            [ text "ɬ" ]
                        , button [ attribute "style" "align-self:right", onClick (InsertText "ɮ") ]
                            [ text "ɮ" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    ]
                , tr []
                    [ th []
                        [ text "Approximant" ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "ʋ") ]
                            [ text "ʋ" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "ɹ") ]
                            [ text "ɹ" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "ɻ") ]
                            [ text "ɻ" ]
                        ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "j") ]
                            [ text "j" ]
                        ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "ɰ") ]
                            [ text "ɰ" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    ]
                , tr []
                    [ th []
                        [ text "Lateral Approximant" ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "l") ]
                            [ text "l" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "ɭ") ]
                            [ text "ɭ" ]
                        ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "ʎ") ]
                            [ text "ʎ" ]
                        ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced", onClick (InsertText "ʟ") ]
                            [ text "ʟ" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    ]
                ]
            , table []
                [ tr []
                    [ td [ attribute "style" "width: 600px;" ]
                        [ h2 []
                            [ text "Consonants (Non-Pulmonic)" ]
                        , table []
                            [ tr []
                                [ th []
                                    [ text "Clicks" ]
                                , th []
                                    [ text "Voiced implosives" ]
                                , th []
                                    [ text "Ejective" ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ onClick (InsertText "ʘ")]
                                        [ text "ʘ" ]
                                    , text "Bilabial"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "ɓ")]
                                        [ text "ɓ" ]
                                    , text "Bilabial"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "ʼ")]
                                        [ text "ʼ" ]
                                    , text "Ejective"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ onClick (InsertText "ǀ")]
                                        [ text "ǀ" ]
                                    , text "Dental  "
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "ɗ")]
                                        [ text "ɗ" ]
                                    , text "Dental/alveolar"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ onClick (InsertText "ǃ")]
                                        [ text "ǃ" ]
                                    , text "(Post)alveolar "
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "ʄ")]
                                        [ text "ʄ" ]
                                    , text "Palatal"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ onClick (InsertText "ǂ")]
                                        [ text "ǂ" ]
                                    , text "Palatoalveolar"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "ɠ")]
                                        [ text "ɠ" ]
                                    , text "Velar"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ onClick (InsertText "ǁ")]
                                        [ text "ǁ" ]
                                    , text "Alveolar lateral"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "ʛ")]
                                        [ text "ʛ" ]
                                    , text "Uvular"
                                    ]
                                ]
                            ]
                        , br []
                            []
                        ]
                    , td [ attribute "style" "width: 600px;" ]
                        [ h2 []
                            [ text "Vowels" ]
                        , br []
                            []
                        , span [ attribute "style" "margin-left:30px" ]
                            [ text "Front" ]
                        , span [ attribute "style" "margin-left:170px" ]
                            [ text "Central" ]
                        , span [ attribute "style" "margin-left:170px" ]
                            [ text "Back" ]
                        , br []
                            []
                        , button [ class "vowel", onClick (InsertText "i") ]
                            [ text "i" ]
                        , button [ class "vowel rounded", onClick (InsertText "y") ]
                            [ text "y" ]
                        , button [ class "vowel", attribute "style" "margin-left:100px", onClick (InsertText "ɨ") ]
                            [ text "ɨ" ]
                        , button [ class "vowel rounded", onClick (InsertText "ʉ") ]
                            [ text "ʉ" ]
                        , button [ class "vowel", attribute "style" "margin-left:100px", onClick (InsertText "ɯ") ]
                            [ text "ɯ" ]
                        , button [ class "vowel rounded", onClick (InsertText "u") ]
                            [ text "u" ]
                        , text "Close            "
                        , br []
                            []
                        , button [ class "vowel", attribute "style" "margin-left:100px", onClick (InsertText "ɪ") ]
                            [ text "ɪ" ]
                        , button [ class "vowel rounded", onClick (InsertText "ʏ") ]
                            [ text "ʏ" ]
                        , button [ class "vowel rounded", attribute "style" "margin-left:150px", onClick (InsertText "ʊ") ]
                            [ text "ʊ" ]
                        , br []
                            []
                        , button [ class "vowel", attribute "style" "margin-left:50px", onClick (InsertText "e") ]
                            [ text "e" ]
                        , button [ class "vowel rounded", onClick (InsertText "ø") ]
                            [ text "ø" ]
                        , button [ class "vowel", attribute "style" "margin-left:50px", onClick (InsertText "ɘ") ]
                            [ text "ɘ" ]
                        , button [ class "vowel rounded", onClick (InsertText "ɵ") ]
                            [ text "ɵ" ]
                        , button [ class "vowel", attribute "style" "margin-left:100px", onClick (InsertText "ɤ") ]
                            [ text "ɤ" ]
                        , button [ class "vowel rounded", onClick (InsertText "o") ]
                            [ text "o" ]
                        , text "Close-mid            "
                        , br []
                            []
                        , button [ class "vowel", attribute "style" "margin-left:230px", onClick (InsertText "ə") ]
                            [ text "ə" ]
                        , br []
                            []
                        , button [ class "vowel", attribute "style" "margin-left:80px", onClick (InsertText "ɛ") ]
                            [ text "ɛ" ]
                        , button [ class "vowel rounded", onClick (InsertText "œ") ]
                            [ text "œ" ]
                        , button [ class "vowel", attribute "style" "margin-left:20px", onClick (InsertText "ɜ") ]
                            [ text "ɜ" ]
                        , button [ class "vowel rounded", onClick (InsertText "ɞ") ]
                            [ text "ɞ" ]
                        , button [ class "vowel", attribute "style" "margin-left:100px", onClick (InsertText "ʌ") ]
                            [ text "ʌ" ]
                        , button [ class "vowel rounded", onClick (InsertText "ɔ") ]
                            [ text "ɔ" ]
                        , text "Open-mid            "
                        , br []
                            []
                        , button [ class "vowel", attribute "style" "margin-left:120px", onClick (InsertText "æ") ]
                            [ text "æ" ]
                        , button [ class "vowel", attribute "style" "margin-left:60px", onClick (InsertText "ɐ") ]
                            [ text "ɐ" ]
                        , br []
                            []
                        , button [ class "vowel", attribute "style" "margin-left:110px", onClick (InsertText "a") ]
                            [ text "a" ]
                        , button [ class "vowel rounded", onClick (InsertText "ɶ") ]
                            [ text "ɶ" ]
                        , button [ class "vowel", attribute "style" "margin-left:200px", onClick (InsertText "ɑ") ]
                            [ text "ɑ" ]
                        , button [ class "vowel rounded", onClick (InsertText "ɒ") ]
                            [ text "ɒ" ]
                        , text "Open        "
                        ]
                    ]
                , tr []
                    [ td []
                        [ h2 []
                            [ text "Other Symbols" ]
                        , table []
                            [ tr []
                                [ td []
                                    [ button [ class "voiceless", onClick (InsertText "ʍ") ]
                                        [ text "ʍ" ]
                                    , text "Voiceless labial-velar fricative"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "ɕ")]
                                        [ text "ɕ" ]
                                    , button [ class "voiced", onClick (InsertText "ʑ") ]
                                        [ text "ʑ" ]
                                    , text "Alveolo-palatal fricatives"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ class "voiced", onClick (InsertText "w") ]
                                        [ text "w" ]
                                    , text "Voiced labial-velar approximant"
                                    ]
                                , td []
                                    [ button [ class "voiced", onClick (InsertText "ɺ") ]
                                        [ text "ɺ" ]
                                    , text "Voiced alveolar lateral flap"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ class "voiced", onClick (InsertText "ɥ") ]
                                        [ text "ɥ" ]
                                    , text "Voiced labial-palatal approximant"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "ɧ")]
                                        [ text "ɧ" ]
                                    , text "Simultaneous ʃ and x"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ class "voiceless", onClick (InsertText "ʜ") ]
                                        [ text "ʜ" ]
                                    , text "Voiceless epiglottal fricative"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ class "voiced", onClick (InsertText "ʢ") ]
                                        [ text "ʢ" ]
                                    , text "Voiced epiglottal fricative"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ onClick (InsertText "ʡ")]
                                        [ text "ʡ" ]
                                    , text "Epiglottal plosive"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "͡")]
                                        [ text "͡" ]
                                    , button [ onClick (InsertText "͜")]
                                        [ text "͜" ]
                                    , text "Double articulation/ affricate"
                                    ]
                                ]
                            ]
                        , br []
                            []
                        , h2 []
                            [ text "Diacritics" ]
                        , table []
                            [ tr []
                                [ td []
                                    [ button [ onClick (InsertText "̥")]
                                        [ text "̥" ]
                                    , button [ onClick (InsertText "̊")]
                                        [ text "̊" ]
                                    , text "Voiceless "
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "̤")]
                                        [ text "̤" ]
                                    , text "Breathy voiced"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "̪")]
                                        [ text "̪" ]
                                    , text "Dental"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ onClick (InsertText "̬")]
                                        [ text "̬" ]
                                    , text "Voiced"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "̰")]
                                        [ text "̰" ]
                                    , text "Creaky voiced"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "̺")]
                                        [ text "̺" ]
                                    , text "Apical"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ onClick (InsertText "ʰ")]
                                        [ text "ʰ" ]
                                    , text "Aspirated"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "̼")]
                                        [ text "̼" ]
                                    , text "Linguolabial"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "̻")]
                                        [ text "̻" ]
                                    , text "Laminal"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ onClick (InsertText "̹")]
                                        [ text "̹" ]
                                    , text "More rounded"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "ʷ")]
                                        [ text "ʷ" ]
                                    , text "Labialised "
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "̃")]
                                        [ text "̃" ]
                                    , text "Nasalised"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ onClick (InsertText "̜")]
                                        [ text "̜" ]
                                    , text "Less rounded"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "ʲ")]
                                        [ text "ʲ" ]
                                    , text "Palatalised"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "ⁿ")]
                                        [ text "ⁿ" ]
                                    , text "Pre/post nasalised"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ onClick (InsertText "̟")]
                                        [ text "̟" ]
                                    , text "Advanced"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "ˠ")]
                                        [ text "ˠ" ]
                                    , text "Velarised"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "ˡ")]
                                        [ text "ˡ" ]
                                    , text "Lateral release"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ onClick (InsertText "̠")]
                                        [ text "̠" ]
                                    , text "Retracted"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "ˤ")]
                                        [ text "ˤ" ]
                                    , text "Pharyngealised"
                                    ]
                                , td []
                                    [ button [ onClick (InsertText "̚")]
                                        [ text "̚" ]
                                    , text "No audible release"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ onClick (InsertText "̈")]
                                        [ text "̈" ]
                                    , text "Centralised"
                                    ]
                                , td []
                                    []
                                ]
                            ]
                        ]
                    ]
                ]
            ]



-- Note: I used an online tool (on March 23, 2020) to translate the HTML I had previously written
-- to Elm source code.
-- You can find that tool at: https://mbylstra.github.io/html-to-elm/

-- I used the following regular expressions to add all the onClick function calls.
--  Find: (button\s*\[\s*(?:class\s*".*?")?.*?)(\s*\]\s*\n\s*\[\s*text\s*)(".*?")
--   $1, onClick (InsertText $3)$2$3
-- The result was not perfect, but worked for most of the cases.