module Main exposing (..)

-- Press buttons to increment and decrement a counter.
--
-- Read how it works:
--   https://guide.elm-lang.org/architecture/buttons.html
--


import Browser
import Html exposing (Html, button, div, text, textarea, b, h1, h2, table, tr, th, td, br, span)
import Html.Attributes exposing (attribute, id, class)
import Html.Events exposing (onClick)



-- MAIN


main =
  Browser.sandbox { init = init, update = update, view = view }



-- MODEL


type alias Model = String


init : Model
init =
  "blank slate"



-- UPDATE


type Msg
  = 
  InsertText String


update : Msg -> Model -> Model
update msg model =
  case msg of
    InsertText str -> 
      model ++ str



-- VIEW


view : Model -> Html Msg
view model =
  div []
            [ textarea [ id "screen" ]
                []
            , b []
                [ text "Press buttons below to write text here." ]
            , h1 []
                [ text "International Phonetic Alphabet" ]
            , h2 []
                [ text "Consonants (Pulmonic)" ]
            , table [ attribute "style" "border: 1px solid black;" ]
                [ tr []
                    [ th []
                        []
                    , th []
                        [ text "Bilabial        " ]
                    , th []
                        [ text "Labio-dental        " ]
                    , th []
                        [ text "Dental        " ]
                    , th []
                        [ text "Alveolar        " ]
                    , th []
                        [ text "Post-alveolar        " ]
                    , th []
                        [ text "Retroflex        " ]
                    , th []
                        [ text "Palatal        " ]
                    , th []
                        [ text "Velar        " ]
                    , th []
                        [ text "Uvular        " ]
                    , th []
                        [ text "Pharyngeal        " ]
                    , th []
                        [ text "Glottal        " ]
                    ]
                , tr []
                    [ th []
                        [ text "Plosive" ]
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "p" ]
                        , button [ class "voiced" ]
                            [ text "b" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "t" ]
                        , button [ class "voiced" ]
                            [ text "d" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "ʈ" ]
                        , button [ class "voiced" ]
                            [ text "ɖ" ]
                        ]
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "c" ]
                        , button [ class "voiced" ]
                            [ text "ɟ" ]
                        ]
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "k" ]
                        , button [ class "voiced" ]
                            [ text "g" ]
                        ]
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "q" ]
                        , button [ class "voiced" ]
                            [ text "ɢ" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "ʔ" ]
                        , button [ attribute "style" "visibility: hidden;" ]
                            []
                        ]
                    ]
                , tr []
                    [ th []
                        [ text "Nasal" ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "m" ]
                        ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "ɱ" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "n" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "ɳ" ]
                        ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "ɲ" ]
                        ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "ɴ" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    ]
                , tr []
                    [ th []
                        [ text "Trill" ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "ʙ" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "r" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "ʀ" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    ]
                , tr []
                    [ th []
                        [ text "Tap or Flap" ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "ⱱ" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "ɾ" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "ɽ" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    ]
                , tr []
                    [ th []
                        [ text "Fricative" ]
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "ɸ" ]
                        , button [ class "voiced" ]
                            [ text "β" ]
                        ]
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "f" ]
                        , button [ class "voiced" ]
                            [ text "v" ]
                        ]
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "θ" ]
                        , button [ class "voiced" ]
                            [ text "ð" ]
                        ]
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "s" ]
                        , button [ class "voiced" ]
                            [ text "z" ]
                        ]
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "ʃ" ]
                        , button [ class "voiced" ]
                            [ text "ʒ" ]
                        ]
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "ʂ" ]
                        , button [ class "voiced" ]
                            [ text "ʐ" ]
                        ]
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "ç" ]
                        , button [ class "voiced" ]
                            [ text "ʝ" ]
                        ]
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "x" ]
                        , button [ class "voiced" ]
                            [ text "ɣ" ]
                        ]
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "χ" ]
                        , button [ class "voiced" ]
                            [ text "ʁ" ]
                        ]
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "ħ" ]
                        , button [ class "voiced" ]
                            [ text "ʕ" ]
                        ]
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "h" ]
                        , button [ class "voiced" ]
                            [ text "ɦ" ]
                        ]
                    ]
                , tr []
                    [ th []
                        [ text "Lateral Fricative" ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        [ button [ class "voiceless" ]
                            [ text "ɬ" ]
                        , button [ attribute "style" "align-self:right" ]
                            [ text "ɮ" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    ]
                , tr []
                    [ th []
                        [ text "Approximant" ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "ʋ" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "ɹ" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "ɻ" ]
                        ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "j" ]
                        ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "ɰ" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    ]
                , tr []
                    [ th []
                        [ text "Lateral Approximant" ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "l" ]
                        ]
                    , td []
                        []
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "ɭ" ]
                        ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "ʎ" ]
                        ]
                    , td []
                        [ button [ attribute "style" "visibility: hidden;" ]
                            []
                        , button [ class "voiced" ]
                            [ text "ʟ" ]
                        ]
                    , td []
                        []
                    , td []
                        []
                    , td []
                        []
                    ]
                ]
            , table []
                [ tr []
                    [ td [ attribute "style" "width: 600px;" ]
                        [ h2 []
                            [ text "Consonants (Non-Pulmonic)" ]
                        , table []
                            [ tr []
                                [ th []
                                    [ text "Clicks" ]
                                , th []
                                    [ text "Voiced implosives" ]
                                , th []
                                    [ text "Ejective" ]
                                ]
                            , tr []
                                [ td []
                                    [ button []
                                        [ text "ʘ" ]
                                    , text "Bilabial"
                                    ]
                                , td []
                                    [ button []
                                        [ text "ɓ" ]
                                    , text "Bilabial"
                                    ]
                                , td []
                                    [ button []
                                        [ text "ʼ" ]
                                    , text "Ejective"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button []
                                        [ text "ǀ" ]
                                    , text "Dental  "
                                    ]
                                , td []
                                    [ button []
                                        [ text "ɗ" ]
                                    , text "Dental/alveolar"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button []
                                        [ text "ǃ" ]
                                    , text "(Post)alveolar "
                                    ]
                                , td []
                                    [ button []
                                        [ text "ʄ" ]
                                    , text "Palatal"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button []
                                        [ text "ǂ" ]
                                    , text "Palatoalveolar"
                                    ]
                                , td []
                                    [ button []
                                        [ text "ɠ" ]
                                    , text "Velar"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button []
                                        [ text "ǁ" ]
                                    , text "Alveolar lateral"
                                    ]
                                , td []
                                    [ button []
                                        [ text "ʛ" ]
                                    , text "Uvular"
                                    ]
                                ]
                            ]
                        , br []
                            []
                        ]
                    , td [ attribute "style" "width: 600px;" ]
                        [ h2 []
                            [ text "Vowels" ]
                        , br []
                            []
                        , span [ attribute "style" "margin-left:30px" ]
                            [ text "Front" ]
                        , span [ attribute "style" "margin-left:170px" ]
                            [ text "Central" ]
                        , span [ attribute "style" "margin-left:170px" ]
                            [ text "Back" ]
                        , br []
                            []
                        , button [ class "vowel" ]
                            [ text "i" ]
                        , button [ class "vowel rounded" ]
                            [ text "y" ]
                        , button [ class "vowel", attribute "style" "margin-left:100px" ]
                            [ text "ɨ" ]
                        , button [ class "vowel rounded" ]
                            [ text "ʉ" ]
                        , button [ class "vowel", attribute "style" "margin-left:100px" ]
                            [ text "ɯ" ]
                        , button [ class "vowel rounded" ]
                            [ text "u" ]
                        , text "Close            "
                        , br []
                            []
                        , button [ class "vowel", attribute "style" "margin-left:100px" ]
                            [ text "ɪ" ]
                        , button [ class "vowel rounded" ]
                            [ text "ʏ" ]
                        , button [ class "vowel rounded", attribute "style" "margin-left:150px" ]
                            [ text "ʊ" ]
                        , br []
                            []
                        , button [ class "vowel", attribute "style" "margin-left:50px" ]
                            [ text "e" ]
                        , button [ class "vowel rounded" ]
                            [ text "ø" ]
                        , button [ class "vowel", attribute "style" "margin-left:50px" ]
                            [ text "ɘ" ]
                        , button [ class "vowel rounded" ]
                            [ text "ɵ" ]
                        , button [ class "vowel", attribute "style" "margin-left:100px" ]
                            [ text "ɤ" ]
                        , button [ class "vowel rounded" ]
                            [ text "o" ]
                        , text "Close-mid            "
                        , br []
                            []
                        , button [ class "vowel", attribute "style" "margin-left:230px" ]
                            [ text "ə" ]
                        , br []
                            []
                        , button [ class "vowel", attribute "style" "margin-left:80px" ]
                            [ text "ɛ" ]
                        , button [ class "vowel rounded" ]
                            [ text "œ" ]
                        , button [ class "vowel", attribute "style" "margin-left:20px" ]
                            [ text "ɜ" ]
                        , button [ class "vowel rounded" ]
                            [ text "ɞ" ]
                        , button [ class "vowel", attribute "style" "margin-left:100px" ]
                            [ text "ʌ" ]
                        , button [ class "vowel rounded" ]
                            [ text "ɔ" ]
                        , text "Open-mid            "
                        , br []
                            []
                        , button [ class "vowel", attribute "style" "margin-left:120px" ]
                            [ text "æ" ]
                        , button [ class "vowel", attribute "style" "margin-left:60px" ]
                            [ text "ɐ" ]
                        , br []
                            []
                        , button [ class "vowel", attribute "style" "margin-left:110px" ]
                            [ text "a" ]
                        , button [ class "vowel rounded" ]
                            [ text "ɶ" ]
                        , button [ class "vowel", attribute "style" "margin-left:200px" ]
                            [ text "ɑ" ]
                        , button [ class "vowel rounded" ]
                            [ text "ɒ" ]
                        , text "Open        "
                        ]
                    ]
                , tr []
                    [ td []
                        [ h2 []
                            [ text "Other Symbols" ]
                        , table []
                            [ tr []
                                [ td []
                                    [ button [ class "voiceless" ]
                                        [ text "ʍ" ]
                                    , text "Voiceless labial-velar fricative"
                                    ]
                                , td []
                                    [ button []
                                        [ text "ɕ" ]
                                    , button [ class "voiced" ]
                                        [ text "ʑ" ]
                                    , text "Alveolo-palatal fricatives"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ class "voiced" ]
                                        [ text "w" ]
                                    , text "Voiced labial-velar approximant"
                                    ]
                                , td []
                                    [ button [ class "voiced" ]
                                        [ text "ɺ" ]
                                    , text "Voiced alveolar lateral flap"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ class "voiced" ]
                                        [ text "ɥ" ]
                                    , text "Voiced labial-palatal approximant"
                                    ]
                                , td []
                                    [ button []
                                        [ text "ɧ" ]
                                    , text "Simultaneous ʃ and x"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ class "voiceless" ]
                                        [ text "ʜ" ]
                                    , text "Voiceless epiglottal fricative"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button [ class "voiced" ]
                                        [ text "ʢ" ]
                                    , text "Voiced epiglottal fricative"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button []
                                        [ text "ʡ" ]
                                    , text "Epiglottal plosive"
                                    ]
                                , td []
                                    [ button []
                                        [ text "͡" ]
                                    , button []
                                        [ text "͜" ]
                                    , text "Double articulation/ affricate"
                                    ]
                                ]
                            ]
                        , br []
                            []
                        , h2 []
                            [ text "Diacritics" ]
                        , table []
                            [ tr []
                                [ td []
                                    [ button []
                                        [ text "̥" ]
                                    , button []
                                        [ text "̊" ]
                                    , text "Voiceless "
                                    ]
                                , td []
                                    [ button []
                                        [ text "̤" ]
                                    , text "Breathy voiced"
                                    ]
                                , td []
                                    [ button []
                                        [ text "̪" ]
                                    , text "Dental"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button []
                                        [ text "̬" ]
                                    , text "Voiced"
                                    ]
                                , td []
                                    [ button []
                                        [ text "̰" ]
                                    , text "Creaky voiced"
                                    ]
                                , td []
                                    [ button []
                                        [ text "̺" ]
                                    , text "Apical"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button []
                                        [ text "ʰ" ]
                                    , text "Aspirated"
                                    ]
                                , td []
                                    [ button []
                                        [ text "̼" ]
                                    , text "Linguolabial"
                                    ]
                                , td []
                                    [ button []
                                        [ text "̻" ]
                                    , text "Laminal"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button []
                                        [ text "̹" ]
                                    , text "More rounded"
                                    ]
                                , td []
                                    [ button []
                                        [ text "ʷ" ]
                                    , text "Labialised "
                                    ]
                                , td []
                                    [ button []
                                        [ text "̃" ]
                                    , text "Nasalised"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button []
                                        [ text "̜" ]
                                    , text "Less rounded"
                                    ]
                                , td []
                                    [ button []
                                        [ text "ʲ" ]
                                    , text "Palatalised"
                                    ]
                                , td []
                                    [ button []
                                        [ text "ⁿ" ]
                                    , text "Pre/post nasalised"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button []
                                        [ text "̟" ]
                                    , text "Advanced"
                                    ]
                                , td []
                                    [ button []
                                        [ text "ˠ" ]
                                    , text "Velarised"
                                    ]
                                , td []
                                    [ button []
                                        [ text "ˡ" ]
                                    , text "Lateral release"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button []
                                        [ text "̠" ]
                                    , text "Retracted"
                                    ]
                                , td []
                                    [ button []
                                        [ text "ˤ" ]
                                    , text "Pharyngealised"
                                    ]
                                , td []
                                    [ button []
                                        [ text "̚" ]
                                    , text "No audible release"
                                    ]
                                ]
                            , tr []
                                [ td []
                                    [ button []
                                        [ text "̈" ]
                                    , text "Centralised"
                                    ]
                                , td []
                                    []
                                ]
                            ]
                        ]
                    ]
                ]
            ]



-- Note: I used an online tool (on March 23, 2020) to translate the HTML I had previously written
-- to Elm source code.
-- You can find that tool at: https://mbylstra.github.io/html-to-elm/